name: deploy_function

on:
  push:
    branches: [main]
    paths: [reception/func]

jobs:
  deploy_function:
    runs-on: ubuntu-latest

    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to azure container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Docker build and push
      run: |
        cd reception/function
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/reception-func:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/reception-func:latest
