name: format-terraform

on:
  push:
    branches: [main]

jobs:
  format-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ secrets.TERRAFORM_VERSION }}

    - name: Check terraform format
      run: terraform fmt -recursive -check
